### PR TITLE
Remove spurious __init__ variables

### PR DESCRIPTION
**Pull request by ahendriksen**
When you execute

In [1]: import human_readable_project_name as he
In [2]: help(he)

The help page would previously show version_file and version_filename
in the DATA section. Deleting these variables after use fixes that
problem.

Is this the right way to fix the problem?

### CODE REVIEW

**Comment by jwbuurlage** [comment]
What do we have to add to make functions show up (without adding `__all__`) in the `help(he)`?

**Comment by ahendriksen** [comment]
I do not know.

**Comment by jwbuurlage** [comment]
I think this is fine for now :+1:

**Comment by dmpelt** [comment]
Ah, I didn't think about the variables polluting the help message.

A different way of fixing this (maybe, I haven't tested it yet) that I think is slightly nicer would be to create a 'private' function that gets the version number from the file. I.e. something like:

```
def __get_version():
    import os.path
    version_filename = os.path.join(os.path.dirname(__file__), 'VERSION')
    with open(version_filename) as version_file:
        version = version_file.read().strip()
    return version

__version__ = __get_version()
```

I'm not sure, but I think `__get_version()` won't show up in help.

About the functions showing up in help -- I don't know what the best way is to do this. Is there a disadvantage to using `__all__`?

**Comment by ahendriksen** [comment]
I am sorry for the bike shedding. I want to get to the bottom of this. Apparently, there are [7 common version resolution methods](https://packaging.python.org/guides/single-sourcing-package-version/). 

Of those methods, I like number 3 the most. An example can be found [here](https://github.com/NLeSC/python-template/commit/b721fb73b2d16c459b525277fb0311e66f3cbbdc). 

It removes the need for a `manifest.in` file and does not require spurious variables in the __init__.py. 

What do you think?

**Comment by dmpelt** [comment]
I still like 4 better -- it is very similar to 3, can be used in other tools as well, and personally I like that the versioning is not coupled with the code.

**Comment by jwbuurlage** [comment]
Thanks for looking into this Allard! I like 3 best since it avoids MANIFEST.in and our template is for a pure Python library anyway.

**Comment by ahendriksen** [comment]
I changed the code to use a private function and am merging. The differences are marginal anyway.

**Comment by dmpelt** [comment]
I'm fine either [way](https://i.kym-cdn.com/photos/images/newsfeed/001/225/438/b0f.gif).

**Pull request merged**
